config/routes.rb
Rails.application.routes.draw do
  root  to: 'toppages#index'
  get 'test', to: 'toppages#test'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/:start_time/diets', to: 'diets#daily_index'
  get '/:start_time/diet', to: 'diets#daily_new'
  get '/twitter/index', to: 'twitter#index'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get :weekly_records
      get :monthly_records
      get :yearly_records
    end
  end
  resources :diets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diet.rb
class Diet < ApplicationRecord
  belongs_to :user
  
  validate :error
  
  before_save do
    self.sugar = ((( self.calorie - self.protein * 4 - self.fat * 9 ) / 4 ) / self.total_amount * self.intake ).round(2)
  end
    
  def error
    if start_time.blank? || name.blank? || total_amount.blank? || intake.blank? || calorie.blank? || protein.blank? || fat.blank? || carb.blank?
      errors[:base] << "未入力の項目があります"
    elsif total_amount < 0 || intake < 0 || calorie < 0 || protein < 0 || fat < 0 || carb < 0
      errors[:base] << "マイナスの値は登録できません"
    elsif name.length > 50
      errors[:base] << "品名は50文字以内で登録してください"
    elsif ((( self.calorie - self.protein * 4 - self.fat * 9 ) / 4 ) / self.total_amount * self.intake ).round(2) < 0
     errors[:base] << "糖質がマイナスの値です"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :diets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to root_path
    end
  end
  
  def set_layout_difference
    @special_twitter = nil
  end
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :set_start_time, only: [:update]
  before_action :set_date, only: [:edit]
  
  def index
    @diets = current_user.diets.order(id: :desc).page(params[:page]).per(25)
  end
  
  def show
    @special_twitter = true
  end
  
  def new
    @diet = current_user.diets.build
  end
  
  def create
    @diet = current_user.diets.build(diet_params)
    set_start_time
    if @diet.save
      flash[:success] = '食事を登録しました'
      redirect_to diet_url(@diet)
    else
      flash[:danger] = '食事の登録に失敗しました'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @diet.update(diet_params)
      flash[:success] = '食事を編集しました'
      redirect_to diet_url(@diet)
    else
      flash[:danger] = '食事の編集に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @diet.destroy
    flash[:success] = '食事を削除しました'
    redirect_to diets_url
  end
  
  def daily_index
    @special_twitter = true
    @diets = current_user.diets.where(start_time: params[:start_time]).order(id: :desc).page(params[:page]).per(25)
  end
  
  def daily_new
    @diet = current_user.diets.build(start_time: params[:start_time])
  end
  
  private
  
  def set_start_time
    if params[:date] == ""
      @diet.start_time = nil
    else
      input_str = params[:date]
      date = Date.strptime(input_str, '%Y-%m-%d')
      @diet.start_time = DateTime.new(date.year, date.month, date.day, 0, 0, 0 )
    end
  end
  
  def set_date
    @date = @diet.start_time.to_date
  end
  
  def diet_params
    params.require(:diet).permit(:name, :total_amount, :intake, :calorie, :protein, :fat, :carb)
  end
  
  def correct_user
    @diet = current_user.diets.find_by(id: params[:id])
    unless @diet
      redirect_to root_url 
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :set_twitter_client

  def index
    @tweets = @twitter.search("#php -rt", lang: 'ja', result_type: "recent").take(3)
  end
  
  def test
  end
  
  private
  
  def set_twitter_client
    @twitter = Twitter::REST::Client.new do |config|
      config.consumer_key        = "I8RVuRZd6F7Bl5e1yQk7t37xR"
      config.consumer_secret     = "BOpNkEXSiV2osZnCNysF9VWJwr8ZAVhHe4XsoBvmw6BCEHYEuu"
      config.access_token        = "2392232876-dxQuYLwSlh4A8qlDaMkPx0gb8kdmPoFAxLYSByN"
      config.access_token_secret = "Wc3psIGmghU8JxBaW6aNhkJRJh7v1vSw2hFfevHnOm9O7"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]
  
  def show
    @diets = Diet.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = '目標を設定しました。'
      redirect_to @user
    else
      flash.now[:danger] = '目標の設定に失敗しました'
      render :edit
    end
  end
  
  def weekly_records
    @weekly_records = Diet.where(user_id: current_user.id, start_time: Date.today.prev_week...Date.tomorrow)
  end
  
  def monthly_records
    @monthly_records = Diet.where(user_id: current_user.id, start_time: Date.today.last_month...Date.tomorrow)
  end
  
  def yearly_records
    @yearly_records = Diet.where(user_id: current_user.id, start_time: Date.today.last_year...Date.tomorrow)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_digest, :goal)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def correct_user
    unless @user == current_user
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diets/_form.html.erb
<div class = "row">
  <div class="offset-md-3 col-md-6 mt-3">
    <%= form_with(model: diet, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <ul class = "list-group mb-3">
        <li class="list-group-item active">
          <%= f.text_field :name, class: 'form-control', placeholder: '品名' %>
        </li>
      
        <li class="list-group-item active">
          <%= date_field_tag :date, type = 'date', value: @date, class: 'form-control' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :total_amount, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '基準量　　　:(gあたり)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :calorie, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: 'カロリー　　:(kcal)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :protein, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: 'たんぱく質　:(g)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :fat, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '脂質　　　　:(g)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :carb, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '炭水化物　　:(g)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :intake, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '摂取量　　　:(g)' %>
        </li>
      </ul>
        
      <%= f.submit '食事登録', class: 'btn btn-info btn-block' %>
    <% end %>
  </div>
</div>

app/views/diets/_list.html.erb
<div class = "row">
  <div class="offset-md-3 col-md-6 mt-3">
    <ul class = "list-group">
      <% diets.each do |diet| %>
        <li class = "list-group-item">
          <div>
            <%= diet.start_time.to_date %>
          </div>
          <div>
            <%= link_to diet.name, diet_path(diet.id) %>　　　　　<%= diet.sugar %> g
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/diets/daily_index.html.erb
<%= render 'list', diets: @diets %>

<%= paginate @diets %> 

<div class = "row">
  <div class="offset-md-3 col-md-6 mt-3">
    <%= link_to '食事登録', {controller: "diets", action: "daily_new", start_time: params[:start_time]}, class: 'btn btn-info btn-block' %>
    <%= link_to '戻る', user_path(current_user.id), class: 'btn btn-secondary btn-block' %>
    
    <footer>
      <div class="text-center mt-5">
        <div class="col-md-1 d-inline">
          <% if current_user.goal %>
            <a target="blank" href="https://twitter.com/intent/tweet?text=今日は<%= @diets.sum(:carb) %>g糖質を摂取しました。目標値<%= current_user.goal %>gまであと<%= @diets.sum(:carb) - current_user.goal %>gです！&url=http://carb-labo.herokuapp.com/&hashtags=carb_lab"><%= image_tag('twitter.png', alt: "twitterアイコン", id: "icon-twitter", class: "icon") %></a>
          <% else %>
            <a target="blank" href="https://twitter.com/intent/tweet?text=今日は<%= @diets.sum(:carb) %>g糖質を摂取しました！&url=http://carb-labo.herokuapp.com/&hashtags=carb_lab"><%= image_tag('twitter.png', alt: "twitterアイコン", id: "icon-twitter", class: "icon") %></a>
          <% end %>
        </div>
        <%= render 'layouts/button' %>
      </div>
    </footer>
  </div>
</div>

app/views/diets/daily_new.html.erb
<div class = "row">
  <div class="offset-md-3 col-md-6 mt-3">
    <%= form_with(model: @diet, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <ul class = "list-group mb-3">
        <li class="list-group-item active">
          <%= f.text_field :name, class: 'form-control', placeholder: '品名' %>
        </li>
      
        <li class="list-group-item active">
          <%= date_field_tag :date, type = 'date', value: @diet.start_time.to_date, class: 'form-control' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :total_amount, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '基準量　　　:(gあたり)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :calorie, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: 'カロリー　　:(kcal)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :protein, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: 'たんぱく質　:(g)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :fat, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '脂質　　　　:(g)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :carb, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '炭水化物　　:(g)' %>
        </li>
        
        <li class="list-group-item">
          <%= f.number_field :intake, step: '0.01',min: '0', class: 'form-control d-inline', placeholder: '摂取量　　　:(g)' %>
        </li>
      </ul>
        
      <%= f.submit '食事登録', class: 'btn btn-info btn-block' %>
    <% end %>
    
    <div class = "mt-2">
      <%= link_to '戻る', {controller: "diets", action: "daily_index", start_time: @diet.start_time}, class: 'btn btn-secondary btn-block' %>
    </div>
   
   </div>
</div>

app/views/diets/edit.html.erb
<%= render 'form', diet: @diet %>

<div class = "row">
  <div class="offset-md-3 col-md-6 mt-2">
    <%= link_to '戻る', diet_path(@diet.id), class: 'btn btn-secondary btn-block' %>
  </div>
</div>

app/views/diets/index.html.erb
<%= render 'list', diets: @diets %>

 <%= paginate @diets %>
 
<%= render 'users/buttons'%>

app/views/diets/new.html.erb
<%= render 'form', diet: @diet %>

app/views/diets/show.html.erb
<div class ="row">
  <div class="offset-md-3 col-md-6">
    <ul class = "list-group mb-3">
      <li class="list-group-item active">
        <h2><%= @diet.name %></h2><%= @diet.start_time.to_date %>
      </li>
      <li class="list-group-item">
        <%= @diet.total_amount %> gあたり
      </li>
      <li class="list-group-item">
        カロリー　　　：<%= @diet.calorie %> kcal
      </li>
      <li class="list-group-item">
        タンパク質　　：<%= @diet.protein %> g
      </li>
      <li class="list-group-item">
        脂質　　　　　：<%= @diet.fat %> g
      </li>
      <li class="list-group-item">
        炭水化物　　　：<%= @diet.carb %> g
      </li>
      <li class="list-group-item">
        摂取量　　　　：<%= @diet.intake %> g
      </li>
      <li class="list-group-item text-danger font-weight-bold">
        摂取糖質量　　：<%= @diet.sugar %> g
      </li>
    </ul>
    <%= link_to '編集', edit_diet_path(@diet), class: 'btn btn-info btn-block' %>
    <%= link_to '削除', @diet, method: :delete, class: 'btn btn-secondary btn-block', data: { confirm: '本当に削除してよろしいですか？' } %>
  
    <footer>
      <div class="text-center mt-5">
        <div class="col-md-1 d-inline">
          <a target="blank" href="https://twitter.com/intent/tweet?text=<%= @diet.name %>を食べて<%= @diet.carb %>g糖質を摂取しました！&url=http://carb-labo.herokuapp.com/&hashtags=carb_lab"><%= image_tag('twitter.png', alt: "twitterアイコン", id: "icon-twitter", class: "icon") %></a>
        </div>
        <%= render 'layouts/button' %>
      </div>
    </footer>
    
  </div>
</div>

app/views/layouts/_button.html.erb
<div class="col-md-1 d-inline">
  <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://carb-labo.herokuapp.com/"><%= image_tag('facebook.png', alt: "facebookアイコン", id: "icon-fb", class: "icon") %></a>
</div>


<div class="col-md-1 d-inline">
  <a target="_blank" href="https://social-plugins.line.me/lineit/share?url=http://carb-labo.herokuapp.com/"><%= image_tag('line.png', alt: "Lineアイコン", id: "icon-line", class: "icon") %></a>
</div> 

<!--<div class="col-md-1 d-inline">-->
<!--  <i class="fab fa-google-plus" id="icon-gplus"></i>-->
<!--</div>-->

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>" ><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-dark bg-info">
    <a class="navbar-brand" href="/">Carb Labo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to current_user.name, user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">食事管理</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to '食事登録', new_diet_path %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to '糖質量推移', weekly_records_user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to '登録一覧', diets_path %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to '目標登録', edit_user_url(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarbLabo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container-fluid mb-4">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
      
      <footer>
        <% if @special_twitter == nil %>
        <div class="offset-md-3 col-md-6 mt-3">
          <div class="text-center mt-5">
            <div class="col-md-1 d-inline">
              <a target="blank" href="https://twitter.com/intent/tweet?text=carb_laboで糖質を管理しよう！&url=http://carb-labo.herokuapp.com/&hashtags=carb_lab"><%= image_tag('twitter.png', alt: "twitterアイコン", id: "icon-twitter", class: "icon") %></a>
            </div>
            <%= render 'layouts/button' %>
          </div>
        </div>
        <% end %>
      </footer>
      
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<div class="row">
  <div class="offset-md-3 col-md-6 mt-3">
    <ul class="list-group">
      <li class="list-group-item active">
        <h1 class="text-center" id="explain-title">What's Carb Labo ?</h1>
      </li>
      <li class = "list-group-item" >
        <p>栄養表示から糖質量を計算するサイトです。<br>
        エネルギー源として重要な糖質(炭水化物の一部)、脂質、たんぱく質を三大栄養素と言います。<br>
        これらを燃焼したとき、体で利用できるエネルギーの値は1gあたり糖質4kcal、脂質9kcal、たんぱく質4kcal程です。</p>
        <p><strong>カロリー(kcal) = 糖質(g)×4kcal + 脂質(g)×9kcal + たんぱく質(g)×4kcal</strong></p>
        <p>上記の考えを利用することにより、カロリーと三大栄養素の量から大まかに糖質量を計算することができます。</p>
        <p><strong>糖質(g) = ( カロリー(kcal) - 脂質(g)×9kcal - たんぱく質(g)×4kcal ) ÷4</strong></p>
        <%= link_to '試しに糖質計算してみる', test_path, class: 'btn btn-info offset-md-3 col-md-6 mt-3 mb-2' %>
      </li>
    </ul>
    <!--<h3>最近のツイート</h3>-->
    <!--<% @tweets.each do |tweet| %>-->
    <!--  <blockquote class="twitter-tweet"><a href="<%= tweet.url %>"></a></blockquote>-->
    <!--<% end %>-->
    <!--<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>-->
    
    <a class="twitter-timeline" href="https://twitter.com/Carb_Labo?ref_src=twsrc%5Etfw">Tweets by Carb_Labo</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <div class="text-right">
      <div class="d-inline mr-3">
        <a href="https://twitter.com/Carb_Labo?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-show-count="false">Follow @Carb_Labo</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
      <div class="d-inline float-right">
        <a href="https://twitter.com/messages/compose?recipient_id=1148992924513755136&ref_src=twsrc%5Etfw" class="twitter-dm-button" data-size="large" data-show-screen-name="false" data-screen-name="https://twitter.com/Carb_Labo" data-show-count="false">Message @https://twitter.com/Carb_Labo</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    </div>
  </div>
</div>

app/views/users/_buttons.html.erb
<div class = "row">
  <div class="offset-md-3 col-md-6 mt-3">
    <%= link_to '食事登録', new_diet_path, class: 'btn btn-info btn-block' %>
    <%= link_to 'ユーザーページへ', user_path(current_user), class: 'btn btn-secondary btn-block' %>
  </div>
</div>

app/views/users/_tabs.html.erb
<ul class="nav nav-tabs mb-3">
  <li class="nav-item"><a href="<%= weekly_records_user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(weekly_records_user_path(current_user)) %>">週</a></li>
  <li class="nav-item"><a href="<%= monthly_records_user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(monthly_records_user_path(current_user)) %>">月</a></li>
  <li class="nav-item"><a href="<%= yearly_records_user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(yearly_records_user_path(current_user)) %>">年</a></li>
</ul>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>目標登録</h1>
</div>

<div class="row">
  <div class="col-md-6 offset-md-3 mt-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.number_field :goal, class: 'form-control', placeholder: '一日あたり糖質摂取量' %>
      </div>
      
      <%= f.submit '目標登録', class: 'btn btn-info btn-block' %>
    <% end %>
    <%= link_to 'ユーザーページへ', user_path(current_user), class: 'btn btn-secondary btn-block mt-2' %>
  </div>
</div>

app/views/users/monthly_records.html.erb
<div class="row">
  <aside class="col-md-6 offset-md-3 mt-3">
    <%= render 'tabs' %>
    <%= area_chart @monthly_records.group_by_day(:start_time).sum(:sugar), xmin: Date.today.last_month, xmax: Date.today, curve: false, messages: {empty: "No data"} %>
  </div>
</div>

<%= render 'buttons'%>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-md-6 offset-md-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード再確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-info btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="offset-md-2 col-md-8">
    
    <% if current_user.goal == nil %>
      <div id="error_explanation" class="alert alert-info">
        目標が設定されていません。登録は<%= link_to 'こちら', edit_user_path(current_user.id) %>
      </div>
    <% end %>
    
    <%= month_calendar events: @diets do |date, diets| %>
      <%= link_to date.day, controller: "diets", action: "daily_index", start_time: date  %>
      
      <!--目標判定-->
      <div class = "mt-3 text-right">
        <% if current_user.goal == nil %>
        <% elsif @diets.where(start_time: date, user_id: current_user.id).sum(:sugar) == 0 %>
          <div class = "text-muted" >
            未入力
          </div>
        <% elsif @diets.where(start_time: date).sum(:sugar) <= current_user.goal %>
          <div class = "text-success" >
            達成
          </div>
        <% else %>
          <div class = "text-danger" >
            未達成
          </div>
        <% end %>
      </div>
      <!--目標判定-->
      
      <!--合計糖質量-->
      <div class = "text-right" >
        <%= @diets.where(start_time: date, user_id: current_user.id).sum(:sugar) %> g
      </div>
      <!--合計糖質量-->
  
    <% end %>
    
    <%= link_to '食事登録', new_diet_path, class: 'btn btn-info btn-block' %>
    <%= link_to '糖質量推移', weekly_records_user_path(current_user), class: 'btn btn-secondary btn-block' %>
  </div>
</div>